In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy

In [5]:
#Creating Array
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
#numpy version
import numpy as np

print(np.__version__)

1.23.5


In [7]:
import numpy

#0-D Array
arr1 = numpy.array(42)
print(arr1)
print('Dimension :',arr1.ndim)

#1-D Array
arr2 = numpy.array([1,2,3,4,5])
print(arr2)
print('Dimension :',arr2.ndim)

#2-D Array
arr3 = numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print('Dimension :',arr3.ndim)

#Dimension---*ndim

42
Dimension : 0
[1 2 3 4 5]
Dimension : 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimension : 2


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

print('Number of dimensions :', arr.ndim)

#Passing Dimension as an argument----*ndmin*

[[[[[1 2 3 4]]]]]
Number of dimensions : 5


In [13]:
#____*Array Indexing*_____

#Accessing Elements of Array

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

2
7


In [12]:
#Accessing 2-D Array

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [14]:
#Accessing 3-D Array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [15]:
#Negative Indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


In [16]:
#___Array Slicing____

#[start:end]
#[start:end:step]

#__Start index alone

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])


[5 6 7]


In [17]:
#End Index Alone

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


In [18]:
#Start and End Index Alone

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [19]:
#Start,End index with Step

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6:2])

[2 4 6]


In [20]:
#Negative Slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [21]:
#__Slicing 2-D Array

#Slicing 2nd row elements

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [22]:
#Slicing 2nd Column elements

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]
